# -*- coding: utf-8 -*-
"""Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iE-jqOnVvbQlm9_JLjxaT9mElgAOdDJL
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("rfm.csv")

features = df[['Recency','Frequency','Monetary']]

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

wcss = []

for i in range(1,11):
    kmeans = KMeans(
        n_clusters=i,
        random_state=42,
        n_init=10
    )

    kmeans.fit(scaled_features)

    wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss)
plt.xlabel("Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df['Cluster'] = kmeans.fit_predict(
    scaled_features
)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(
    df['Recency'],
    df['Monetary'],
    c=df['Cluster']
)

plt.xlabel("Recency")
plt.ylabel("Monetary")
plt.title("Customer Segments")
plt.show()

print(df[['Recency','Frequency','Monetary']].describe())

cluster_summary = df.groupby('Cluster')[['Recency','Frequency','Monetary']].mean()
print(cluster_summary)

cluster_names = {
    0: "Hibernating",
    1: "Loyal",
    2: "High Value",
    3: "Champions"
}

df["Segment"] = df["Cluster"].map(cluster_names)

segment_counts = (
    df["Segment"]
    .value_counts()
)

print(segment_counts)

import matplotlib.pyplot as plt

segment_counts = df["Segment"].value_counts()

plt.figure(figsize=(8,5))

segment_counts.plot(kind="bar")

plt.title("Customer Segment Distribution")
plt.xlabel("Segment")
plt.ylabel("Number of Customers")

plt.show()

print(df["Segment"].value_counts())

df.to_csv("segment_results.csv", index=False)