# -*- coding: utf-8 -*-
"""inventory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTIBrQbPPG97YR8VFk6uHU0qsurH2udr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('cleaned_data_v2.csv')
print(df.shape)
df.head()

inventory = (
    df.groupby(
        ["StockCode", "Description"]
    )
    .agg({
        "Revenue":"sum",
        "Quantity":"sum"
    })
    .reset_index()
)

inventory.head()

inventory = inventory.sort_values(
    by="Revenue",
    ascending=False
)

inventory.head()

inventory["Cumulative_Revenue"] = (
    inventory["Revenue"].cumsum()
)

inventory["Cumulative_Percentage"] = (
    inventory["Cumulative_Revenue"]
    / inventory["Revenue"].sum()
) * 100

def abc_category(x):

    if x <= 80:
        return "A"

    elif x <= 95:
        return "B"

    else:
        return "C"

inventory["ABC_Category"] = (
    inventory["Cumulative_Percentage"]
    .apply(abc_category)
)

inventory.head(10)

print(
    inventory["ABC_Category"]
    .value_counts()
)

inventory["ABC_Category"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.title("ABC Inventory Analysis")
plt.ylabel("")
plt.show()

def inventory_risk(q):

    if q < 100:
        return "High Risk"

    elif q < 500:
        return "Medium Risk"

    else:
        return "Low Risk"

inventory["Inventory_Risk"] = (
    inventory["Quantity"]
    .apply(inventory_risk)
)

inventory["Reorder"] = (
    inventory["Inventory_Risk"]
    .map({
        "High Risk":"YES",
        "Medium Risk":"Monitor",
        "Low Risk":"NO"
    })
)

inventory["Inventory_Risk"] \
    .value_counts() \
    .plot(kind="bar")

plt.title("Inventory Risk Distribution")
plt.xlabel("Risk Level")
plt.ylabel("Number of Products")

plt.show()

top10 = inventory.nlargest(
    10,
    "Revenue"
)

print(top10)

inventory.to_csv(
    "inventory_analysis.csv",
    index=False
)

print("Inventory Analysis Saved")

